services:
  wedding-api:
    build: .
    volumes:
      - wedding-data:/data
    restart: unless-stopped
    networks:
      - wedding_net
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel-wedding_api
    restart: always
    command: tunnel run --token ${CLOUDFLARE_TOKEN}
    networks:
      - wedding_net

networks:
  wedding_net:
    driver: bridge

volumes:
  wedding-data:
